sequenceDiagram
    actor Op as Despachador
    participant FE as React
    participant GW as Gateway
    participant BFF as bff-rev
    participant MI as ms-incidentes
    participant MZ as ms-zonas
    participant MR as ms-recursos
    Op->>FE: 1 Login
    Op->>FE: 2 Dashboard
    FE->>GW: GET /api/dashboard
    GW->>BFF: Forward
    BFF->>MI: Listar
    BFF->>MZ: Riesgo
    BFF->>MR: Recursos
    Op->>FE: 3 Crear / 5 Asignar
    BFF->>MR: Asignación
