gitGraph
    commit id: "init"
    branch dev
    checkout dev
    commit id: "integración"
    branch feature/portal
    commit id: "FEAT portal"
    checkout dev
    merge feature/portal
    checkout main
    merge dev id: "release EVA2"
