flowchart LR
    INC[ms-incidentes<br/>:8081]
    ZON[ms-zonas-riesgo<br/>:8082]
    REC[ms-recursos<br/>:8083]
    BFF[bff-rev]
    UI[Dashboard React]
    INC --> BFF
    ZON --> BFF
    REC --> BFF
    BFF --> UI
