server:
  port: ${SERVER_PORT:18080}

rev:
  gateway:
    keycloak-roles-url: http://KEYCLOAK-ADAPTER/roles

spring:
  application:
    name: api-gateway
  codec:
    max-in-memory-size: 64MB
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: bff_public_route
              uri: lb://BFF-REV
              predicates:
                - Path=/api/public/**
              filters:
                - name: PublicRateLimitFilter
                  args:
                    maxRequests: 5
                    windowSeconds: 3600
            - id: bff_route
              uri: lb://BFF-REV
              predicates:
                - Path=/api/**
              filters:
                - AuthenticationFilter
            - id: auth_route
              uri: lb://KEYCLOAK-ADAPTER
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:18761/eureka/}

logging:
  level:
    "[org.springframework.cloud.gateway]": INFO
