eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.hostname=ms-zonas-riesgo
eureka.instance.prefer-ip-address=false
spring.datasource.url=jdbc:postgresql://postgres-zonas:5432/rev_zonas
