spring.application.name=MS-ZONAS-RIESGO
server.port=${SERVER_PORT:18082}

eureka.client.serviceUrl.defaultZone=${EUREKA_URL:http://localhost:18761/eureka/}
management.endpoints.web.exposure.include=health,info

spring.datasource.url=jdbc:postgresql://${POSTGRES_ZONAS_HOST:localhost}:${POSTGRES_ZONAS_PORT:15433}/${POSTGRES_ZONAS_DB:rev_zonas}
spring.datasource.username=${POSTGRES_ZONAS_USER:rev}
spring.datasource.password=${POSTGRES_ZONAS_PASSWORD:rev123}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true
