spring.application.name=MS-RECURSOS
server.port=${SERVER_PORT:18083}

eureka.client.serviceUrl.defaultZone=${EUREKA_URL:http://localhost:18761/eureka/}
management.endpoints.web.exposure.include=health,info

spring.datasource.url=jdbc:postgresql://${POSTGRES_RECURSOS_HOST:localhost}:${POSTGRES_RECURSOS_PORT:15434}/${POSTGRES_RECURSOS_DB:rev_recursos}
spring.datasource.username=${POSTGRES_RECURSOS_USER:rev}
spring.datasource.password=${POSTGRES_RECURSOS_PASSWORD:rev123}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true
