eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.hostname=ms-recursos
eureka.instance.prefer-ip-address=false
spring.datasource.url=jdbc:postgresql://postgres-recursos:5432/rev_recursos
