spring.application.name=BFF-REV
server.port=8085

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
management.endpoints.web.exposure.include=health,info,circuitbreakers

resilience4j.circuitbreaker.instances.zonasRiesgo.slidingWindowSize=10
resilience4j.circuitbreaker.instances.zonasRiesgo.failureRateThreshold=50
resilience4j.circuitbreaker.instances.zonasRiesgo.waitDurationInOpenState=5s

resilience4j.circuitbreaker.instances.recursos.slidingWindowSize=10
resilience4j.circuitbreaker.instances.recursos.failureRateThreshold=50
resilience4j.circuitbreaker.instances.recursos.waitDurationInOpenState=5s

rev.public-report.min-form-seconds=3
rev.public-report.turnstile-secret=${TURNSTILE_SECRET_KEY:disabled}

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=60MB
