eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.hostname=keycloak-adapter
eureka.instance.prefer-ip-address=false
keycloak.token-uri=http://keycloak:8080/realms/rev/protocol/openid-connect/token
keycloak.user-info-uri=http://keycloak:8080/realms/rev/protocol/openid-connect/userinfo
keycloak.logout=http://keycloak:8080/realms/rev/protocol/openid-connect/logout
keycloak.jwk-set-uri=http://keycloak:8080/realms/rev/protocol/openid-connect/certs
