spring.application.name=KEYCLOAK-ADAPTER
server.port=8088
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

keycloak.token-uri=${KEYCLOAK_URL:http://localhost:8090}/realms/rev/protocol/openid-connect/token
keycloak.user-info-uri=${KEYCLOAK_URL:http://localhost:8090}/realms/rev/protocol/openid-connect/userinfo
keycloak.logout=${KEYCLOAK_URL:http://localhost:8090}/realms/rev/protocol/openid-connect/logout
keycloak.jwk-set-uri=${KEYCLOAK_URL:http://localhost:8090}/realms/rev/protocol/openid-connect/certs
keycloak.certs-id=${KEYCLOAK_CERTS_ID:}

keycloak.client-id=${KEYCLOAK_CLIENT_ID:rev-frontend}
keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET:rev-dev-secret}
keycloak.scope=profile
keycloak.authorization-grant-type=password
keycloak.authorization-grant-type-refresh=refresh_token
