spring.application.name=KEYCLOAK-ADAPTER
server.port=${SERVER_PORT:18088}
eureka.client.serviceUrl.defaultZone=${EUREKA_URL:http://localhost:18761/eureka/}

keycloak.token-uri=${KEYCLOAK_URL:http://localhost:18090}/realms/rev/protocol/openid-connect/token
keycloak.user-info-uri=${KEYCLOAK_URL:http://localhost:18090}/realms/rev/protocol/openid-connect/userinfo
keycloak.logout=${KEYCLOAK_URL:http://localhost:18090}/realms/rev/protocol/openid-connect/logout
keycloak.jwk-set-uri=${KEYCLOAK_URL:http://localhost:18090}/realms/rev/protocol/openid-connect/certs
keycloak.certs-id=${KEYCLOAK_CERTS_ID:}

keycloak.client-id=${KEYCLOAK_CLIENT_ID:rev-frontend}
keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET:rev-dev-secret}
keycloak.scope=profile
keycloak.authorization-grant-type=password
keycloak.authorization-grant-type-refresh=refresh_token

keycloak.admin.server-url=${KEYCLOAK_URL:http://localhost:18090}
keycloak.admin.realm=rev
keycloak.admin.master-realm=master
keycloak.admin.username=admin
keycloak.admin.password=admin
keycloak.admin.client-id=admin-cli
