spring.application.name=MS-INCIDENTES
server.port=8081

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
management.endpoints.web.exposure.include=health,info

spring.datasource.url=jdbc:postgresql://${POSTGRES_INCIDENTES_HOST:localhost}:${POSTGRES_INCIDENTES_PORT:5432}/${POSTGRES_INCIDENTES_DB:rev_incidentes}
spring.datasource.username=${POSTGRES_INCIDENTES_USER:rev}
spring.datasource.password=${POSTGRES_INCIDENTES_PASSWORD:rev123}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true

rev.storage.path=${REV_STORAGE_PATH:./data/incidente-adjuntos}
rev.storage.max-photo-bytes=5242880
rev.storage.max-video-bytes=52428800

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=60MB
