spring.application.name=MS-INCIDENTES
server.port=${SERVER_PORT:18081}

eureka.client.serviceUrl.defaultZone=${EUREKA_URL:http://localhost:18761/eureka/}
management.endpoints.web.exposure.include=health,info

spring.datasource.url=jdbc:postgresql://${POSTGRES_INCIDENTES_HOST:localhost}:${POSTGRES_INCIDENTES_PORT:15432}/${POSTGRES_INCIDENTES_DB:rev_incidentes}
spring.datasource.username=${POSTGRES_INCIDENTES_USER:rev}
spring.datasource.password=${POSTGRES_INCIDENTES_PASSWORD:rev123}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true

rev.correlacion.umbral-score=60
rev.correlacion.default-radio-metros=500
rev.correlacion.default-ventana-minutos=90
rev.correlacion.tipos.URBANO.radio-metros=400
rev.correlacion.tipos.URBANO.ventana-minutos=90
rev.correlacion.tipos.FORESTAL.radio-metros=2000
rev.correlacion.tipos.FORESTAL.ventana-minutos=180
rev.correlacion.tipos.ESTRUCTURAL.radio-metros=300
rev.correlacion.tipos.ESTRUCTURAL.ventana-minutos=120

rev.storage.path=${REV_STORAGE_PATH:./data/incidente-adjuntos}
rev.storage.max-photo-bytes=5242880
rev.storage.max-video-bytes=52428800

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=60MB
